micronaut:
  application:
    name: creativeyann17-github-api
  server:
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins:
            - https://creativeyann17.github.io
datasources:
  default:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    dialect: POSTGRES
jpa:
  default:
    entity-scan:
      packages: com.creativeyann17.github.api.domain
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
endpoints:
  all:
    enabled: false
    sensitive: false
  health:
    enabled: true
logger:
  levels:
    com.creativeyann17.github.api: INFO
